//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1882
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.1882.
// 
namespace GPSProxy.SerialPort.ServiceWrapper {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IGPSManager", Namespace="http://tempuri.org/")]
    public partial class GPSManager : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public GPSManager() {
            this.Url = "http://localhost:2481/GPSManager.svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IGPSManager/CreateNewPath", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateNewPath([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] PathInfo path, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UserInfo user, out bool CreateNewPathResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CreateNewPathResultSpecified) {
            object[] results = this.Invoke("CreateNewPath", new object[] {
                        path,
                        user});
            CreateNewPathResult = ((bool)(results[0]));
            CreateNewPathResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateNewPath(PathInfo path, UserInfo user, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateNewPath", new object[] {
                        path,
                        user}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreateNewPath(System.IAsyncResult asyncResult, out bool CreateNewPathResult, out bool CreateNewPathResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            CreateNewPathResult = ((bool)(results[0]));
            CreateNewPathResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IGPSManager/GetPathList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/GPSProxy.GPSService")]
        public PathInfo[] GetPathList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string searchString, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UserInfo user) {
            object[] results = this.Invoke("GetPathList", new object[] {
                        searchString,
                        user});
            return ((PathInfo[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPathList(string searchString, UserInfo user, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPathList", new object[] {
                        searchString,
                        user}, callback, asyncState);
        }
        
        /// <remarks/>
        public PathInfo[] EndGetPathList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PathInfo[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IGPSManager/UploadGPSData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UploadGPSData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] GPSUploadData data, out bool UploadGPSDataResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool UploadGPSDataResultSpecified) {
            object[] results = this.Invoke("UploadGPSData", new object[] {
                        data});
            UploadGPSDataResult = ((bool)(results[0]));
            UploadGPSDataResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUploadGPSData(GPSUploadData data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UploadGPSData", new object[] {
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUploadGPSData(System.IAsyncResult asyncResult, out bool UploadGPSDataResult, out bool UploadGPSDataResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            UploadGPSDataResult = ((bool)(results[0]));
            UploadGPSDataResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IGPSManager/GetGPSData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/GPSProxy.GPSService")]
        public GPSDownloadData[] GetGPSData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] GPSDataRequestParameter para) {
            object[] results = this.Invoke("GetGPSData", new object[] {
                        para});
            return ((GPSDownloadData[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetGPSData(GPSDataRequestParameter para, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetGPSData", new object[] {
                        para}, callback, asyncState);
        }
        
        /// <remarks/>
        public GPSDownloadData[] EndGetGPSData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GPSDownloadData[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IGPSManager/GetPathID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetPathID([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] PathInfo path, out int GetPathIDResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool GetPathIDResultSpecified) {
            object[] results = this.Invoke("GetPathID", new object[] {
                        path});
            GetPathIDResult = ((int)(results[0]));
            GetPathIDResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPathID(PathInfo path, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPathID", new object[] {
                        path}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndGetPathID(System.IAsyncResult asyncResult, out int GetPathIDResult, out bool GetPathIDResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            GetPathIDResult = ((int)(results[0]));
            GetPathIDResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IGPSManager/IsServiceAvailable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IsServiceAvailable([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string msg, out bool IsServiceAvailableResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool IsServiceAvailableResultSpecified) {
            object[] results = this.Invoke("IsServiceAvailable", new object[] {
                        msg});
            IsServiceAvailableResult = ((bool)(results[0]));
            IsServiceAvailableResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsServiceAvailable(string msg, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsServiceAvailable", new object[] {
                        msg}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndIsServiceAvailable(System.IAsyncResult asyncResult, out bool IsServiceAvailableResult, out bool IsServiceAvailableResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            IsServiceAvailableResult = ((bool)(results[0]));
            IsServiceAvailableResultSpecified = ((bool)(results[1]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/GPSProxy.GPSService")]
    public partial class PathInfo {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private string passwordField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/GPSProxy.GPSService")]
    public partial class GPSDownloadData {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nMEASentenceField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NMEASentence {
            get {
                return this.nMEASentenceField;
            }
            set {
                this.nMEASentenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/GPSProxy.GPSService")]
    public partial class GPSDataRequestParameter {
        
        private int lastDataIDField;
        
        private bool lastDataIDFieldSpecified;
        
        private bool latestDataOnlyField;
        
        private bool latestDataOnlyFieldSpecified;
        
        private int maxLinesField;
        
        private bool maxLinesFieldSpecified;
        
        private int pathIDField;
        
        private bool pathIDFieldSpecified;
        
        private string pathPasswordField;
        
        /// <remarks/>
        public int LastDataID {
            get {
                return this.lastDataIDField;
            }
            set {
                this.lastDataIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastDataIDSpecified {
            get {
                return this.lastDataIDFieldSpecified;
            }
            set {
                this.lastDataIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool LatestDataOnly {
            get {
                return this.latestDataOnlyField;
            }
            set {
                this.latestDataOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatestDataOnlySpecified {
            get {
                return this.latestDataOnlyFieldSpecified;
            }
            set {
                this.latestDataOnlyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int MaxLines {
            get {
                return this.maxLinesField;
            }
            set {
                this.maxLinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxLinesSpecified {
            get {
                return this.maxLinesFieldSpecified;
            }
            set {
                this.maxLinesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int PathID {
            get {
                return this.pathIDField;
            }
            set {
                this.pathIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PathIDSpecified {
            get {
                return this.pathIDFieldSpecified;
            }
            set {
                this.pathIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PathPassword {
            get {
                return this.pathPasswordField;
            }
            set {
                this.pathPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/GPSProxy.GPSService")]
    public partial class GPSUploadData {
        
        private string nMEASentenceField;
        
        private int pathIDField;
        
        private bool pathIDFieldSpecified;
        
        private string pathPasswordField;
        
        private string providerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NMEASentence {
            get {
                return this.nMEASentenceField;
            }
            set {
                this.nMEASentenceField = value;
            }
        }
        
        /// <remarks/>
        public int PathID {
            get {
                return this.pathIDField;
            }
            set {
                this.pathIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PathIDSpecified {
            get {
                return this.pathIDFieldSpecified;
            }
            set {
                this.pathIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PathPassword {
            get {
                return this.pathPasswordField;
            }
            set {
                this.pathPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/GPSProxy.GPSService")]
    public partial class UserInfo {
        
        private string nameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
}
